### ISSUE TITLE
TypeError: firebaseHackernews is not a function

### ISSUE THREAD

**Issue by naval200** [ragingwind/firebase-hackernews#4]
Running firebase-hackernews in browser throws following error.

Link:

https://npm.runkit.com/firebase-hackernews

Source:

var firebase = require('firebase');
var firebaseHackernews = require("firebase-hackernews")
var hnservice = firebaseHackernews(firebase)
hnservice.stories('top').then(stories => {
    console.log(stories);
})

On running it:-

TypeError: firebaseHackernews is not a function

Solution:-

Fix the documentation.

>>> firebaseHackernews.init(firebase)

**Comment by ragingwind** [comment]
Thanks. closed with https://github.com/ragingwind/firebase-hackernews/commit/534a48fc72b82e0d722f71e9d091a32c26bfdefa
