### ISSUE TITLE
React Native : Can't Find Variable performance

### ISSUE THREAD

**Issue by aswinmohanme** [ragingwind/firebase-hackernews#5]
I'm following the react example and included the neccesary files. When the App runs the Following Error Message is displayed and the data is not fetched.

Possible Unhandled Promise Rejection

Reference Error: Can't find Variable: performance

**Comment by aswinmohanme** [comment]
The error crops up from this line, `window` is defined in React Native but `performance` is not. 
https://github.com/ragingwind/firebase-hackernews/blob/edbe79b17123e54bf30b32e6d4316db4920b83af/src/hackernews.js#L3

Why can't we use Date.now() exclusively, performance.now() is slower(ironically)

**Comment by ragingwind** [comment]
not for native environment. https://developer.mozilla.org/en-US/docs/Web/API/Performance

**Comment by ragingwind** [comment]
using [official apis](https://github.com/tastejs/hacker-news-pwas/blob/master/docs/api.md) instead of
