### ISSUE TITLE
Doens't build with node 10.16

### ISSUE THREAD

**Issue by ElChache** [ragingwind/firebase-hackernews#6]
When trying to add into any project, I get the following error:
`yarn add firebase-hackernews`
```
gyp ERR! cwd /opt/apps/[...]/node_modules/firebase-hackernews/node_modules/grpc
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```
I tried to use it locally with `npm link` and it worked once I updated the firebase dependency to `"firebase": "6.3.3"`

**Comment by ragingwind** [comment]
Sorry this project is not maintained anymore. use official apis instead of. https://github.com/tastejs/hacker-news-pwas/blob/master/docs/api.md
